name: Build Tkinter Application with PyInstaller using Pipenv

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install Pipenv
      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      # Step 4: Install dependencies using Pipenv
      - name: Install dependencies with Pipenv
        run: |
          pipenv install --dev  # Install both regular and dev dependencies

      # Step 5: Get the virtual environment path
      - name: Get virtual environment path
        id: pipenv
        run: |
          VENV_PATH=$(pipenv --venv)
          echo "Virtual environment path: $VENV_PATH"
          echo "::set-output name=venv_path::$VENV_PATH"

      # Step 6: Build the application using PyInstaller
      - name: Build with PyInstaller
        run: |
          pipenv run pyinstaller --paths "${{ steps.pipenv.outputs.venv_path }}" --noconsole --onefile main.py

      # Step 7: Upload the built executable as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: TkinterApp
          path: dist/  # PyInstaller outputs the executable in the 'dist' folder